#!/bin/bash
#
# Simple tool to prepare or remove a temporary working directory for a Kattis problem
#

print_usage () {
    echo $"Usage: $0 get|rm problem"
    exit 1
}

get_problem () {
    PROBLEM=$1
    PROBLEM_URL="https://open.kattis.com/problems/$PROBLEM"
    SAMPLE_URL="$PROBLEM_URL/file/statement/samples.zip"
    ZIP_FILE="$PROBLEM/samples.zip"
    mkdir $PROBLEM
    wget $SAMPLE_URL -O $ZIP_FILE
    unzip $ZIP_FILE -d $PROBLEM/
    printf "# %s%s\n\nfrom sys import stdin" "$KATTIS_URL" > $PROBLEM/$PROBLEM.py
}

if [ -z $1 ] || [ -z $2 ]
then
    print_usage
else
    if [ -z $3 ]
    then
        COMMAND=$1
        PROBLEM=$2
    else
        print_usage
    fi
fi

case "$COMMAND" in
    get)
        get_problem $PROBLEM
        ;;
    rm)
        rm -rf $PROBLEM/
        ;;
    *)
        print_usage
esac
